sudo: required
services:
  - docker
before_install:
  - docker build -t zgalp/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true zgalp/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-875708341793"
  bucket_path: "docker"
  on:
    all_branches: true
  #   branches:
  #     only:
  #       - main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"